"use strict";
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const root = __dirname;
const policy = {
  schema: 1, version: "ca-referencia-2026-09-v1", issuedAt: "2026-09-10T00:00:00Z", expiresAt: "2026-12-10T00:00:00Z",
  status: "referencia_publica_no_aprobada_por_banco",
  bank: { nombre: "Caja de Ahorros · referencia para pruebas", dominios_oficiales: ["cajadeahorros.com.pa", "www.cajadeahorros.com.pa", "ecaja.cajadeahorros.com.pa"],
    telefonos_oficiales: [], acortadores: ["bit.ly", "tinyurl.com", "t.co", "cutt.ly", "is.gd", "rb.gy"] },
};
// Build-time pinning: public key ships inside SDK/application, never trusted from API.
// This development key is NOT an institutional signing identity.
const local = path.join(root, ".local");
fs.mkdirSync(local, { recursive: true, mode: 0o700 });
const keyPath = path.join(local, "policy-private.pem");
if (!fs.existsSync(keyPath)) fs.writeFileSync(keyPath, crypto.generateKeyPairSync("ed25519").privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
const privateKey = crypto.createPrivateKey(fs.readFileSync(keyPath));
const publicKey = crypto.createPublicKey(privateKey);
const payload = Buffer.from(JSON.stringify(policy));
const envelope = { payload: payload.toString("base64"), signature: crypto.sign(null, payload, privateKey).toString("base64") };
const spki = publicKey.export({ type: "spki", format: "der" });
const pinnedKey = spki.subarray(-32).toString("base64");
const rules = fs.readFileSync(path.join(root, "../lib/reglas.js"), "utf8");
const sdk = fs.readFileSync(path.join(root, "sdk/index.js"), "utf8");
const bundle = `// Generated by pilot/build.js. Source: lib/reglas.js and pilot/sdk/index.js.\n(function(g){\nconst r={exports:{}};(function(module){${rules}\n})(r);\nconst s={exports:{}};(function(module,require){${sdk}\n})(s,()=>r.exports);g.Certiva=s.exports;\n})(globalThis);\n`;
for (const dir of ["public", "ios/Sources/CertivaSDK/Resources", "android-app/sdk/src/main/assets"]) {
  const dest = path.join(root, dir); fs.mkdirSync(dest, { recursive: true });
  fs.writeFileSync(path.join(dest, "certiva.js"), bundle);
  fs.writeFileSync(path.join(dest, "policy.json"), JSON.stringify(envelope, null, 2) + "\n");
  fs.writeFileSync(path.join(dest, "policy-key.txt"), pinnedKey + "\n");
}
fs.writeFileSync(path.join(root, "public/policy-key.js"), `globalThis.CERTIVA_POLICY_KEY=${JSON.stringify(pinnedKey)};\n`);
console.log("SDK y política de desarrollo firmada generados. Sin cambios de vigencia automáticos.");
